name: Deploy PWA

on:
  push:
    branches:
      - main
    paths:
      - 'basketball-pwa/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd basketball-pwa
          npm install

      - name: Build PWA
        run: |
          cd basketball-pwa
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./basketball-pwa/dist
          cname: basketball.yourdomain.com  # 如果你有自定义域名，取消注释并修改这行