name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
      env:
        GITHUB_PAGES: 'true'

    - name: Build Electron app
      run: npm run electron:build

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: electron-app
        path: dist/
        compression-level: 0